checks all mandatory files

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,7 +6,7 @@
 #    By: abessa-m <abessa-m@student.42porto.com>    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/10/22 13:21:39 by abessa-m          #+#    #+#              #
-#    Updated: 2024/10/25 07:56:13 by abessa-m         ###   ########.fr        #
+#    Updated: 2024/10/25 09:10:49 by abessa-m         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -18,20 +18,22 @@ TEST = main_test.c
 CC = cc
 CFLAGS = -Wall -Werror -Wextra
 
-OBJS = $(SRCS:.c=.o)
+# Filter only existing source files
+EXISTING_SRCS = $(wildcard $(SRCS))
+OBJS = $(EXISTING_SRCS:.c=.o)
 
 %.o: %.c
 	@$(CC) $(CFLAGS) -c $< -o $@
 
-$(OBJS):
-	@cc -Wall -Werror -Wextra $(SRCS)
+$(OBJS): check-sources
+	@cc -Wall -Werror -Wextra $(EXISTING_SRCS)
 
 SRCS = $(MANDATORY1)
 # $(MANDATORY2) $(BONUS) $(PERSONAL)
 
 MANDATORY1 = ft_isalpha.c ft_isdigit.c ft_isalnum.c \
 	ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c \
-#	ft_strlen.c ft_strlen.c ft_strlcpy.c ft_strlcat.c strchr.c strrchr.c ft_strncmp.c strnstr.c \
+	ft_strlen.c ft_strlen.c ft_strlcpy.c ft_strlcat.c strchr.c strrchr.c ft_strncmp.c strnstr.c \
 	memset.c memcpy.c memmove.c memchr.c memcmp.c \
 	bzero.c \
 	atoi.c
@@ -44,25 +46,38 @@ MANDATORY1 = ft_isalpha.c ft_isdigit.c ft_isalnum.c \
 
 test: re
 	clear
-	@for src in $(SRCS); do \
-		norminette $$src | grep -q "Error!" && echo "$$src:\033[41m  norminette ERROR!\033[0m | " || printf "$$src:\033[0;32m  norminette OK\033[0m | "; \
-		cc -Wall -Werror -Wextra $(TEST) -L. -lft -o a.out; \
-		@valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "definitely lost" && echo "\033[41mvalgrind ERROR!\033[0m" || echo "\033[0;32mvalgrind OK\033[0m"; \
-		./a.out $$src; \
-	done
 	@rm -f a.out
+	@for src in $(SRCS); do \
+		if [ ! -f $$src ]; then \
+			echo "$$src: \033[41mFile not found!\033[0m"; \
+		fi; \
+		if [ -f $$src ]; then \
+			norminette $$src | grep -q "Error!" && echo "$$src:\033[41m  norminette ERROR!\033[0m | " || printf "$$src:\033[0;32m  norminette OK\033[0m | "; \
+			cc -Wall -Werror -Wextra $(TEST) -L. -lft -o a.out; \
+			valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "definitely lost" && echo "\033[41mvalgrind ERROR!\033[0m" || echo "\033[0;32mvalgrind OK\033[0m"; \
+			./a.out $$src; \
+		fi; \
+	done
 
 all: $(NAME)
 
 # example usage: print-SRCS
 print-%: ; @echo '$(subst ','\'',$*=$($*))'
-	@echo ' value = $(value $*)' 
+	@echo ' value = $(value $*)'
 	@echo ' origin = $(origin $*)'
 	@echo ' flavor = $(flavor $*)'
 # original:
 # print-%: ; @echo $*=$($*)
 
-$(NAME): $(OBJS)
+# Add check-sources target that just warns about missing files
+check-sources:
+	@for src in $(SRCS); do \
+		if [ ! -f $$src ]; then \
+			echo "\033[0;93mWarning: Source file '$$src' not found - skipping\033[0m"; \
+		fi; \
+	done
+
+$(NAME): check-sources $(OBJS)
 	@ar rcs $(NAME) $(OBJS)
 	@rm -f $(OBJS)
 
@@ -75,4 +90,4 @@ fclean: clean
 
 re: fclean all
 
-.PHONY: clean fclean re test
+.PHONY: clean fclean re test check-sources
