t_size_t definied

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,7 +6,7 @@
 #    By: abessa-m <abessa-m@student.42porto.com>    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/10/22 13:21:39 by abessa-m          #+#    #+#              #
-#    Updated: 2024/10/25 09:10:49 by abessa-m         ###   ########.fr        #
+#    Updated: 2024/10/25 10:04:01 by abessa-m         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -33,7 +33,7 @@ SRCS = $(MANDATORY1)
 
 MANDATORY1 = ft_isalpha.c ft_isdigit.c ft_isalnum.c \
 	ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c \
-	ft_strlen.c ft_strlen.c ft_strlcpy.c ft_strlcat.c strchr.c strrchr.c ft_strncmp.c strnstr.c \
+	ft_strlen.c ft_strlcpy.c ft_strlcat.c strchr.c strrchr.c ft_strncmp.c strnstr.c \
 	memset.c memcpy.c memmove.c memchr.c memcmp.c \
 	bzero.c \
 	atoi.c
@@ -49,12 +49,12 @@ test: re
 	@rm -f a.out
 	@for src in $(SRCS); do \
 		if [ ! -f $$src ]; then \
-			echo "$$src: \033[41mFile not found!\033[0m"; \
+			echo "$$src: \033[0;93mFile not found!\033[0m"; \
 		fi; \
 		if [ -f $$src ]; then \
-			norminette $$src | grep -q "Error!" && echo "$$src:\033[41m  norminette ERROR!\033[0m | " || printf "$$src:\033[0;32m  norminette OK\033[0m | "; \
+			norminette $$src | grep -q "Error!" && printf "$$src:  \033[41mnorminette ERROR!\033[0m | " || printf "$$src:\033[0;32m  norminette OK\033[0m | "; \
 			cc -Wall -Werror -Wextra $(TEST) -L. -lft -o a.out; \
-			valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "definitely lost" && echo "\033[41mvalgrind ERROR!\033[0m" || echo "\033[0;32mvalgrind OK\033[0m"; \
+			valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "definitely lost" && printf "\033[41mvalgrind ERROR!\033[0m" || echo "\033[0;32mvalgrind OK\033[0m"; \
 			./a.out $$src; \
 		fi; \
 	done
