strchr test

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,7 +6,7 @@
 #    By: abessa-m <abessa-m@student.42porto.com>    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/10/22 13:21:39 by abessa-m          #+#    #+#              #
-#    Updated: 2024/10/25 16:48:06 by abessa-m         ###   ########.fr        #
+#    Updated: 2024/10/26 13:53:02 by abessa-m         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -32,10 +32,10 @@ SRCS = $(MANDATORY1)
 # $(MANDATORY2) $(BONUS) $(PERSONAL)
 
 MANDATORY1 = \
-	ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strnstr.c \
-	ft_memset.c ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c \
 	ft_bzero.c \
 	ft_atoi.c \
+	ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strnstr.c \
+	ft_memset.c ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c \
 	ft_isalpha.c ft_isdigit.c ft_isalnum.c \
 	ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c 
 
@@ -45,6 +45,8 @@ MANDATORY1 = \
 #BONUS = 0
 #	TODO or delete"
 
+all: $(NAME)
+
 test: re
 	clear
 	@rm -f a.out
@@ -53,14 +55,13 @@ test: re
 			echo "$$src: \033[0;93mFile not found!\033[0m"; \
 		fi; \
 		if [ -f $$src ]; then \
-			norminette $$src | grep -q "Error!" && printf "$$src:  \033[41mnorminette ERROR!\033[0m | " || printf "$$src:\033[0;32m  norminette OK\033[0m | "; \
+			norminette $$src | grep -q "Error!" && printf "$$src:  \033[41mnorminette ERROR!\033[0m" || printf "$$src:\033[0;32m  norminette OK\033[0m"; \
+			printf " | \033[41m"; \
 			cc -Wall -Werror -Wextra $(TEST) -L. -lft -o a.out; \
-			valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "definitely lost" && printf "\033[41mvalgrind ERROR!\033[0m" || echo "\033[0;32mvalgrind OK\033[0m"; \
+			valgrind --leak-check=full --show-leak-kinds=all ./a.out $$src 2>&1 | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && printf "\033[0;32m valgrind OK\033[0m\n" || echo "\033[41m valgrind ERROR!\033[0m"; \
 			./a.out $$src; \
 		fi; \
 	done
-
-all: $(NAME)
 
 # example usage: print-SRCS
 print-%: ; @echo '$(subst ','\'',$*=$($*))'
@@ -84,7 +85,7 @@ $(NAME): check-sources $(OBJS)
 
 clean:
 	@rm -f $(OBJS)
-	clear
+#	clear
 
 fclean: clean
 	@rm -f $(NAME)
